name: auto_vehicle
channels:
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - pyqt=4.11.4
    - pip:
        - tensorflow-gpu
        - keras
